config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :rooms
resources :users
resources :reserves

get "/" => "home#top"

get "login" => "users#login_form"
post "login" => "users#login"
post "logout" => "users#logout"

get "search" => "rooms#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  belongs_to :room
  belongs_to :user
  validates :start_day, :end_day, :number_of_people, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reserves
  validates :name, :introduction, :address, :room_image, presence: true
  validates :price, numericality: {only_integer: true}
  mount_uploader :room_image, ImageUploader

private
  def self.erea(search)
    Room.where("address LIKE?","%#{search}%")
  end
  def self.keyword(search)
    Room.where("(address LIKE?) OR (introduction LIKE?) OR (name LIKE?)",
    "%#{search}%","%#{search}%","%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :password, confirmation: true, on: :password_change
  validates :password_confirmation, presence: true, on: :password_change
  validates :name, :email, presence: true
  has_secure_password
  mount_uploader :user_image, ImageUploader
  has_many :posts, dependent: :destroy
  has_many :reserves
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def set_current_user
    if session[:id]
      @user = User.find(session[:id])
    end
  end

  def authenticate_user
    if @user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to login_path
    end
  end

  def ensure_correct_user
    if session[:id] != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to user_path(@user)
    end
  end

  def set_current_room
    @room = Room.find(params[:id])
  end

  def ensure_correct_room
    if session[:id] != @room.user_id
      flash[:notice] = "権限がありません"
      redirect_to user_path(@user)
    end
  end

  def forbid_login_user
    if session[:id]
      flash[:notice] ="すでにログインしています"
      redirect_to user_path(session[:id])
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  
  before_action :set_current_user
  before_action :authenticate_user

  def index
    @reserves = Reserve.where(user_id: session[:id])
    
  end

  def new
    @reserve = Reserve.new
    @user = User.find(session[:id])
    @room = Room.find(params[:room_id])
    if params[:start_day].empty? || params[:end_day].empty?
      flash[:error] = "日付を入力してください"
      redirect_to room_path(@room)
    
    elsif params[:number_of_people].to_s !~ /^[0-9]+$/
      flash[:error] = "人数を半角数字で入力してください"
      redirect_to room_path(@room)
    end
    
  end

  def create
    @reserve = Reserve.new(reserve_params)
    if @reserve.save
      flash[:notice] ="予約が完了しました"
      redirect_to user_path(session[:id])
    end
  end

  private
  def reserve_params
    params.require(:reserve).permit(:start_day, :end_day, :number_of_people, :user_id, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_current_user, {only:[:new, :create, :show, :edit, :update]}
  before_action :authenticate_user, {only: [:edit, :update]}
  before_action :set_current_room, {only: [:show, :edit]}
  before_action :ensure_correct_room, {only: [:edit, :update]}

  def index
    @rooms = Room.where(user_id: session[:id])
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:notice] = "ルームを登録しました"
      redirect_to user_path(@user)
    else
      flash[:error_message] = @room.errors.full_messages
      flash[:name] = @room.name
      flash[:introduction] = @room.introduction
      flash[:price] = @room.price
      flash[:address] = @room.address
      redirect_to new_room_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = "編集しました"
      redirect_to room_path(@room)
    else
      render "edit"
    end
  end

  def destroy
    
  end

  def search
    if params[:erea_search].present?
      @rooms = Room.erea(params[:erea_search])
    elsif params[:keyword_search].present?
      @rooms = Room.keyword(params[:keyword_search])
    else
      @rooms = Room.all
      @all = "all"
    end
  end

  private
  def room_params
    params.require(:room).permit(:name, :introduction, :price, :address, :room_image, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_current_user, {only:[:show, :edit, :update]}
  before_action :authenticate_user, {only: [:show, :edit, :update]}
  before_action :ensure_correct_user,{only: [:edit, :update]}
  before_action :forbid_login_user, {only: [:login, :login_form, :new, :create]}
  def index
  end

  def show
  end

  def new
    @user = User.new
  end
    
  def create
    @user = User.new(user_params)
    if @user.save(content: :password_change)
      session[:id] = @user.id
      flash[:notice] = "アカウントを作成しました"
      redirect_to user_path(session[:id])
    else
      flash[:error_message] = @user.errors.full_messages
      flash[:name] = @user.name
      flash[:email] = @user.email
      flash[:password] = @user.password
      redirect_to new_user_path
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "変更しました"
      redirect_to user_path(session[:id])
    else
      render "edit"
    end
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:email])

    if @user&.authenticate(params[:password])
      flash[:notice] = "ログインしました"
      session[:id] = @user.id
      redirect_to user_path(session[:id])
    else
      @email = params[:email]
      @password = params[:password]
      @error_message = "メールアドレスまたはパスワードが間違っています"
      render "login_form"
    end
  end

  def logout
    session[:id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to "/"
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduction, :user_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="first_image_container">
  <div class="first_search">
    <h3>RoomReserveで<br>旅行しよう</h3>
    <%= form_with url:search_path, :method => "get" do |f|%>
      <%= f.text_field :erea_search, :placeholder => "エリア検索"%>
      <%= f.submit "検索する"%>
    <%end%>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoomReserveApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://unpkg.com/sanitize.css" rel="stylesheet"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- googleフォント導入 -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
    <!-- ここまで -->
  </head>
  <header>
    <div>
      <%=link_to image_tag("/assets/logo.png", class: "top_logo"), "/" %>
      <%= form_with url:search_path, :class => "search", :method => "get" do |f|%>
        <%= f.text_field :erea_search, :placeholder => "エリア検索" %>
        <%= f.text_field :keyword_search, :placeholder => "キーワード検索" %>
        <%= f.submit :class => "submit"%>
      <%end%>
    </div>
    <div>
      <%if session[:id] %>
        <%= link_to "マイページ", user_path(session[:id]) %>
        <%= link_to "ログアウト", logout_path, method: :post%>
      <% else %>
        <%= link_to "アカウント作成", new_user_path %>
        <%= link_to "ログイン", login_path %>
      <% end %>
    </div>
  </header>
  
  <div class="main-wrapper">
    <div class="notice">
      <%= flash[:notice] %>
    </div>
    <body>
      <%= yield %>
    </body>
  </div>
  <footer>
    
    <p id="footer_logo"> ©️ 2022 Yamada.INC.</p>
  </footer>
</html>

app/views/reserves/index.html.erb
<div class="contents_wrapper">
  <div class="main_contents">
    <h2>予約ルーム一覧</h2>
    <% if @reserves.empty?%>
      <div class="note">
        <a>予約ルームはありません<a>
      </div>
    <%end%>

    <% @reserves.each do |res|%>
      <div class="reserve_wrapper">
        <div class="reserve_info">
          <div class="reserve_image">
            <img src="<%= res.room.room_image%>">
          </div>
          <div class="reserve_contents">
            <h3>ルーム名</h3>
            <p><%= res.room.name %></p>
            <h3>開始日</h3>
            <p><%= res.start_day %></p>
            <h3>終了日</h3>
            <p><%= res.end_day %></p>
            <h3>予約確定日</h3>
            <p><%= res.created_at.strftime("%Y-%m-%d")%></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="sub_menu">
    <ul>
      <li><%= link_to "マイページ", user_path(session[:id]) %></li>
      <li><%= link_to "ユーザー情報の編集", edit_user_path(session[:id]) %></li>
      <li><%= link_to "ルームの登録", new_room_path %></li>
      <li><%= link_to "登録ルーム一覧", rooms_path %></li>
      <li><%= link_to "予約ルーム一覧", reserves_path %></li>
    </ul>
  </div>
</div>

app/views/reserves/new.html.erb
<div class="form_wrapper">
  <p>ルーム予約</p>
  <%= form_with model: @reserve do |f|%>
    <div class="form_content">
      <p><%= f.date_field :start_day, value: params[:start_day] %></p>
    </div>
    <div class="form_content">
      <p><%= f.date_field :end_day, value: params[:end_day] %></p>
    </div>
    <div class="form_content">
      <p><%= f.text_field :number_of_people, value: params[:number_of_people] %></p>
    </div>
    <div>
      
    <p>合計金額　<%= (params[:end_day].to_date - params[:start_day].to_date).to_i * @room.price * params[:number_of_people].to_i%>
    </div>
    <%= f.hidden_field :user_id, value: params[:user_id]%>
    <%= f.hidden_field :room_id, value: params[:room_id]%>
    
    <%= f.submit "予約確定", :class => "create_btn" %>
  <% end %>
  <div>
    <%=link_to "マイページに戻る", user_path(@user) %>
  </div>
  
</div>

app/views/rooms/edit.html.erb
<div class="form_wrapper">
  <p>ルームの編集</p>
  <%= form_with model: @room do |f|%>
    <div class="form_content">
      <%= f.text_field :name, :placeholder => "ルーム名" %>
    </div>
    <div class="form_content">
      <%= f.text_field :introduction, :placeholder => "ルーム紹介文" %>
    </div>
    <div class="form_content">
      <%= f.text_field :price, :placeholder => "料金" %>
    </div>
    <div class="form_content">
      <%= f.text_field :address, :placeholder => "住所"%>
    </div>
    <div class="form_content">
      <%= f.label :room_image, "ルーム画像アップロード", :class=> "image_input_btn"%>
      <%= f.file_field :room_image, :class => "image_form"%>
    </div>
    <% if flash[:error_message].present? %>
      <% flash[:error_message].each do |error| %>
        <div>
          <%=error%>
        </div>
      <% end %>
    <% end %>
    <%= f.submit "ルームの登録", :class => "create_btn" %>
  <% end %>
  <div>
    <%= link_to "マイページに戻る", user_path(@user) %>
  </div>
  
</div>

app/views/rooms/index.html.erb
<div class="contents_wrapper">
  <div class="main_contents">
    <%if @rooms.present?%>
      <h2>ユーザー登録ルーム一覧 <%=@rooms.count%>件</h2>
    <%else%>
      <h2>登録ルームがありません</h2>
    <%end%>
    <div class="content_list">
      <% @rooms.each do |room|%>
        <div class="content_wrapper">
          <%= link_to room_path(room) do%>
            <div class="border">
              <div class="room_image">
                <img src="<%= room.room_image%>">
              </div>
              <div class="contents">
                <h3>ルーム名</h3>
                <%=room.name%>
                <h3>料金</h3>
                <%=room.price%>
                <h3>住所</h3>
                <%=room.address%>
              </div>
            </div>
          <%end%>
        </div>
      <% end %>
    </div>
  </div>
  <div class="sub_menu">
    <ul>
      <li><%= link_to "マイページ", user_path(session[:id]) %></li>
      <li><%= link_to "ユーザー情報の編集", edit_user_path(session[:id]) %></li>
      <li><%= link_to "ルームの登録", new_room_path %></li>
      <li><%= link_to "登録ルーム一覧", rooms_path %></li>
      <li><%= link_to "予約ルーム一覧", reserves_path %></li>
    </ul>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="contents_wrapper">
  <div class="form_wrapper">
    <p>ルームの登録</p>
    <%= form_with model: @room do |f|%>
      <div class="form_content">
        <p><span>必須</span><%= f.text_field :name, :placeholder => "ルーム名", :value => flash[:name] %></p>
      </div>
      <div class="form_content">
        <p><span>必須</span><%= f.text_field :introduction, :placeholder => "ルーム紹介文", :value => flash[:introduction] %></p>
      </div>
      <div class="form_content">
        <p><span>必須</span><%= f.text_field :price, :placeholder => "料金", :value => flash[:price] %></p>
      </div>
      <div class="form_content">
        <p><span>必須</span><%= f.text_field :address, :placeholder => "住所", :value => flash[:address] %></p>
      </div>
      <div class="form_content">
        <p><span>必須</span>
        <%= f.label :room_image, "ルーム画像アップロード", :class => "image_input_btn"%>
        <%= f.file_field :room_image, :class => "image_form" %></p>
      </div>
      <%= f.hidden_field :user_id, value:@user.id %>
      <% if flash[:error_message].present? %>
        <% flash[:error_message].each do |error| %>
          <div>
            <%=error%>
          </div>
        <% end %>
      <% end %>
      <%= f.submit "ルームの登録", :class => "create_btn" %>
    <% end %>
    <div>
      <%=link_to "マイページに戻る", user_path(@user) %>
    </div>
  </div>
  <div class="sub_menu">
    <ul>
      <li><%= link_to "マイページ", user_path(@user) %></li>
      <li><%= link_to "ユーザー情報の編集", edit_user_path(@user) %></li>
      <li><%= link_to "ルームの登録", new_room_path %></li>
      <li><%= link_to "登録ルーム一覧", rooms_path %></li>
      <li><%= link_to "予約ルーム一覧", reserves_path %></li>
    </ul>
  </div>
</div>

app/views/rooms/search.html.erb
<% if @all.present? %>
  <div class="note">
    <p>検索ワードに一致するものがありませんでした。全件表示します。</p>
  </div>
    <h2>検索結果 <%= @rooms.count %>件</h2>
<% else %>
  <h2>検索結果 <%= @rooms.count %>件</h2>
<% end %>
<div class="content_list">
  <% @rooms.each do |room|%>
    <div class="content_wrapper">
      <%= link_to room_path(room) do %>
        <div class="border">
          <div class="room_image">
            <img src="<%= room.room_image%>">
          </div>
          <div class="contents">
            <h3>ルーム名</h3>
            <%=room.name%>
            <h3>料金</h3>
            <%=room.price%>
            <h3>住所</h3>
            <%=room.address%>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/rooms/show.html.erb
<h2>ルーム詳細ページ</h2>
<div class="room_wrapper">
  <div class="room_info">
    <div class="room_show_image">
      <img src="<%= @room.room_image %>">
    </div>
    <div class="room_contents">
      <h3>ルーム名</h3>
      <p><%=@room.name%></p>
      <h3>紹介文</h3>
      <p><%=@room.introduction%></p>
      <h3>１日宿泊料金</h3>
      <p><%=@room.price%>円</p>
      <h3>住所</h3>
      <p><%=@room.address%></p>
      <% if session[:id] == @room.user_id %>
        <%= link_to "ルーム編集", edit_room_path(@room)%>
      <% end %>
      
      <% if @user.present? %>
        <%= link_to "ルーム一覧に戻る", rooms_path %>
        <div>
          <%= form_with url: new_reserve_path, method: :get do |f|%>
            <div class="form_content">
              <p>開始日<%= f.date_field :start_day %></p>
            </div>
            <div class="form_content">
              <p>終了日<%= f.date_field :end_day%></p>
            </div>
            <div class="form_content">
              <p>人数<%= f.text_field :number_of_people %></p>
            </div>
            
            <%= f.hidden_field :user_id, value:@user.id %>
            <%= f.hidden_field :room_id, value:@room.id %>
            <% if flash[:error].present? %>
              <%= flash[:error] %>
            <% end %>
            <div>
              <%= f.submit "予約する", :class => "create_btn" %>
            </div>
          <% end %>
        </div>
      <% else %>
        <p class="note">ルームを予約するにはログインしてください</p>
        <div>
          <%= link_to "ログインページはこちら", login_path %>
        </div>
        <%= link_to "新規会員登録はこちら", new_user_path %>
      <% end %>  
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="contents_wrapper">
  <div class="form_wrapper">
    <p>アカウントの編集</p>
    <%= form_with model: @user do |f|%>
      <div class="form_content">
        <%= f.text_field :name, :placeholder => "ユーザー名" %>
      </div>
      <div class="form_content">
        <%= f.text_area :introduction, :placeholder => "自己紹介" %>
      </div>
      <div>
        <%= f.label :user_image, "ユーザー画像選択", :class => "image_input_btn" %>
        <%= f.file_field :user_image, :class => "image_form" %>
      </div>
      <%= f.submit "アカウント編集内容の保存", :class => "create_btn edit_form" %>
    <% end %>
    <div>
      <%=link_to "マイページへ戻る", user_path(@user)%>
    </div>
  </div>
  <div class="sub_menu">
    <ul>
      <li><%= link_to "マイページ", user_path(@user) %></li>
      <li><%= link_to "ユーザー情報の編集", edit_user_path(@user) %></li>
      <li><%= link_to "ルームの登録", new_room_path %></li>
      <li><%= link_to "登録ルーム一覧", rooms_path %></li>
      <li><%= link_to "予約ルーム一覧", reserves_path %></li>
    </ul>
  </div>
</div>

app/views/users/login_form.html.erb
<div class="form_wrapper">
  <p>ログインする</p>
  <%= form_with model: @user do |f|%>
    <div class="form_content">
      <%= f.text_field :email, :placeholder => "メールアドレス",:value => @email %>
    </div>
    <div class="form_content">
      <%= f.text_field :password, :placeholder => "パスワード",:value => @password, :type => "password" %>
    </div>
    <div class="error_message">
      <%= @error_message %>
    </div>
    <%= f.submit "ログイン", :class => "create_btn" %>
  <% end %>
  <div>
    <%= link_to "アカウント作成はこちら", new_user_path %>
  </div>
  
</div>

app/views/users/new.html.erb
<div class="form_wrapper">
  <p>新しいアカウントを作成する</p>
  <%= form_with model: @user do |f|%>
    <div class="form_content">
      <a><span>必須</span><%= f.text_field :name, :placeholder => "ユーザー名", :value => flash[:name] %></a>
    </div>
    <div class="form_content">
      <a><span>必須</span><%= f.text_field :email, :placeholder => "メールアドレス", :value => flash[:email] %></a>
    </div>
    <div class="form_content">
      <a><span>必須</span><%= f.text_field :password, :placeholder => "パスワード", :value => flash[:password] %></a>
    </div>
    <div class="form_content">
      <a><span>必須</span><%= f.text_field :password_confirmation, :placeholder => "パスワード確認"%></a>
    </div>
    <% if flash[:error_message].present? %>
      <% flash[:error_message].each do |error| %>
        <div>
          <%=error%>
        </div>
      <% end %>
    <% end %>
    <%= f.submit "アカウントの作成", :class => "create_btn" %>
  <% end %>
  <div>
    <%=link_to "ログインページはこちら",login_path %>
  </div>
  
</div>

app/views/users/show.html.erb
<div class="contents_wrapper">
  <div class="user_info">
    <h2>ユーザーページ</h2>
    <div class="user_image">
      <% if @user.user_image? %>
        <img src="<%= @user.user_image %>">
      <% else %>
        <img src="/assets/default.jpeg">
      <% end %>
    </div>
    <table>
      <tr>
        <th>名前</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>自己紹介</th>
        <td><%= @user.introduction%></td>
      </tr>
    </table>
  </div>
  <div class="sub_menu">
    <ul>
      <li><%= link_to "マイページ", user_path(@user) %></li>
      <li><%= link_to "ユーザー情報の編集", edit_user_path(@user) %></li>
      <li><%= link_to "ルームの登録", new_room_path %></li>
      <li><%= link_to "登録ルーム一覧", rooms_path %></li>
      <li><%= link_to "予約ルーム一覧", reserves_path %></li>
    </ul>
  </div>
</div>